config/routes.rb
Rails.application.routes.draw do
  root "searches#search"

  get "account" => "users#account"

  #検索機能
  get "search" => "searches#search"


  devise_for :users

  resources :users, only: [] do #crudのルートを作成せず、以下のルートのみを作成
    member do #特定のユーザーに紐づくアクションを定義するスコープを作成(id)
      get :reservations # /users/:id/reservations のルートを作成　予約一覧の取得
    end
  end

  resources :rooms do
    resources :reserves, only: [:new, :create, :destroy] # RoomモデルにReserveモデルをネスト
  end
end

app/models/room.rb
class Room < ApplicationRecord
    #画像アップロード
    mount_uploader :image, ImgUploader

    has_many :reserves, class_name: 'Reserve'	#1ユーザーが1回の予約で1つの部屋を予約する(複数予約可） class_nameはReserfeで読み込まれエラー発生のため
    has_many :users, through: :reserves #部屋を予約したユーザーを取得

    #必須項目
    validates  :name, :address, :price,  presence: true
    #価格が1円以上
    validates :price, numericality: { greater_than_or_equal_to: 1 }

  # 検索機能 _search.html
  def self.looks(search, word) #クラスメソッド Room.looks
    if search == "forward_match"
      @searches = Room.where("address LIKE?","#{word}%") #searchesコントローラへ部屋の住所情報を渡す
    elsif search == "partial_match"
      @searches = Room.where("address LIKE?","%#{word}%")
    else
      @searches = Room.none
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ] #各工程の前に@roomを呼び出す
  before_action :authorize_admin, only: [:new, :create] # 管理者以外が直接URL (/rooms/new) にアクセスするのを防ぐ


  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_path, status: :see_other, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:image, :name, :address, :price, :intro)
    end

    # 管理者以外が直接URL (/rooms/new) にアクセスするのを防ぐ
    def authorize_admin
      redirect_to root_path, alert: 'アクセス権限がありません。' unless current_user&.admin?
    end



end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div class="room_form">
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="room_field">
    <%= form.label :image, "画像" %>
    <%= form.file_field :image %>
  </div>

  <div class="room_field">
    <%= form.label :name, "名前" %>
    <%= form.text_field :name %>
  </div>

  <div class="room_field">
    <%= form.label :address, "住所" %>
    <%= form.text_field :address, placeholder: "東京都" %>
  </div>

  <div class="room_field">
    <%= form.label :price, "1泊あたりの価格" %>
    <%= form.text_field :price %>
  </div>

  <div class="room_field">
    <%= form.label :intro, "説明" %>
    <%= form.text_area :intro %>
  </div>

  <div class="room_actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="room_index">
<h1>部屋一覧</h1>
</div>

<div class="new_room_link">
  <!-- 指定ユーザーのみ表示 -->
  <% if current_user&.admin? %> 
    <%= link_to '新規部屋追加', new_room_path %>
  <% end %>
    <%= link_to '検索', search_path %>
</div>

<div class="hotel_index">
    <% @rooms.each do |room| %>
      <ul>
        <li><%= image_tag(room.image.present? ? room.image.url : "https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png") %></li>
        <li class="hotel_name"><%= room.name %></li>
        <li class="hotel_address"><%= room.address %></li>
        <li class="hotel_intro"><%= room.intro %></li>
        <li class="hotel_price">¥<%= room.price %>~</li>
        <li class="hotel_show_link"><%= link_to '詳細はこちら', new_room_reserf_path(room_id: room.id) %></li> <!--予約画面へ-->
      </ul>
    <% end %>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<div class="room_index_link"><%= link_to '戻る', rooms_path %></div> <!--部屋一覧へ-->

<div class="hotel_show">
    <div class="hotel_show_image">
    <%= image_tag(@room.image.present? ? @room.image.url : "https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png") %>
    </div>

    <div class="hotel_show_index">
    <p class="hotel_show_name"><%= @room.name %></p>
    <p class="hotel_show_address"><%= @room.address %></p>
    <p class="hotel_show_price"><%= @room.price %></p>
    <p class="hotel_show_intro"><%= @room.intro %></p>
    </div>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to "予約画面へ", new_room_reserf_path(@room), class: "btn btn-primary" %> <!-- reserves#new -->
</div>