config/routes.rb
Rails.application.routes.draw do
  root "searches#search"

  get "account" => "users#account"

  #検索機能
  get "search" => "searches#search"


  devise_for :users

  resources :users, only: [] do #crudのルートを作成せず、以下のルートのみを作成
    member do #特定のユーザーに紐づくアクションを定義するスコープを作成(id)
      get :reservations # /users/:id/reservations のルートを作成　予約一覧の取得
    end
  end

  resources :rooms do
    resources :reserves, only: [:new, :create, :destroy] # RoomモデルにReserveモデルをネスト
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <div class="top">
      <h1>
        <%= link_to search_path do %>
        <%= image_tag("https://rails-02-sample.herokuapp.com/assets/common/logo.png", alt: "Potepan_Share") %>
        <% end %>
      </h1>

      <!-- ログインユーザー -->
      <% if user_signed_in? %>
        <!-- ユーザー名をクリックするとメニューが開く  script.js-->
      <p>ログイン中: <span class="user-name" id="user-name"><%= current_user.email %></span><span id="dropdown-toggle" class="dropdown-arrow">▼</span></p>
      <ul id="dropdown-menu" class="dropdown-menu hidden">
        <li><%= link_to "予約一覧", reservations_user_path(current_user, room_id: 4) %></li>
        <li><%= link_to 'プロフィール', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？'} %></li>
      </ul>
        <!-- ユーザーのメニュー -->
        <div class="user-menu" id="user-menu">
          <%= link_to '予約一覧', reservations_user_path(current_user.id) %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %>
        </div>
      <% else %>
        <div class="header_login"><%= link_to 'ログイン', new_user_session_path %></div>
        <div class="header_sign_up"><%= link_to '新規登録', new_user_registration_path %></div>
      <% end %>
    </div> 
  </header>

  <!--フラッシュメッセージ-->
  <% if notice %>
    <div class="flash notice"><%= notice %></div>
  <% end %>

  <% if alert %>
    <div class="flash alert"><%= alert %></div>
  <% end %>


    <%= yield %>
  </body>
</html>